logo: # add logo name
title: Welcome to my gallery!
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/mygallery" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: MY VIEW ON WORLD # add banner title
banner-desc: The broader the view, the less the assertions. # add banner description

# Author settings
author-pic: face2.jpg # your photo
author-name: Ranke TAO # your name
about-author: NOBODY # about author
email: shuaiyangtao@hotmail.com # your email
phone: 1234-5678 # your pnone number
website: https://dwayne.example.com # you website

# Social link
weibo_url: https://weibo.com/login.php # add url link
twitter_url:   # add url link
instagram_url: # add url link
youtube_url: # add url link
qq_url: https://www.qq.com/ # add url link
weixin_url: https://mp.weixin.qq.com/ # add url link

# Disqus
discus_identifier: mr-brown # add your discus identifier.  Not your username.  To get this, register your forum here with a unique ID: https://disqus.com/admin/create/

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins_dir:
  - jekyll-paginate
  - jekyll-sitemap

gems:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
